In [1]:
import numpy as np
import pandas as pd
import math, random
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from mpl_toolkits import mplot3d

In [2]:
df = pd.read_csv("train.csv", index_col=0)
dft = pd.read_csv("test.csv", index_col=0)
df

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [3]:
nan=float('nan')

In [4]:
filled=df["Age"][df["Age"].apply(math.isnan).apply(lambda x: not x)]
df["Age"][df["Age"].apply(math.isnan)]=filled.mean()
df["Sex"]=df["Sex"].map({"male":1,"female":2})
df["Cabin"][df["Cabin"].apply(lambda x: type(x)==float and math.isnan(x))]="U"
#cabin_names = ["U","C","E","G","D","A","B","F","T"]
#df["Cabin"].apply(lambda x: x[0])
df["Embarked"][df["Embarked"].apply(lambda x: type(x)==float and math.isnan(x))]="U"
df["Embarked"] = df["Embarked"].map({"S":-3, "C":-1, "Q": 1, "U": 3})
df["Parch"][df["Parch"].apply(lambda x: type(x)==float and math.isnan(x))]=0
df["SibSp"][df["SibSp"].apply(lambda x: type(x)==float and math.isnan(x))]=0
df["Fare"][df["Fare"].apply(lambda x: type(x)==float and math.isnan(x))]=0
filled=dft["Age"][dft["Age"].apply(math.isnan).apply(lambda x: not x)]
dft["Age"][dft["Age"].apply(math.isnan)]=filled.mean()
dft["Sex"]=dft["Sex"].map({"male":1,"female":2})
dft["Cabin"][dft["Cabin"].apply(lambda x: type(x)==float and math.isnan(x))]="U"
#cabin_names = ["U","C","E","G","D","A","B","F","T"]
#df["Cabin"].apply(lambda x: x[0])
dft["Embarked"][dft["Embarked"].apply(lambda x: type(x)==float and math.isnan(x))]="U"
dft["Embarked"] = dft["Embarked"].map({"S":-3, "C":-1, "Q": 1, "U": 3})
dft["Parch"][dft["Parch"].apply(lambda x: type(x)==float and math.isnan(x))]=0
dft["SibSp"][dft["SibSp"].apply(lambda x: type(x)==float and math.isnan(x))]=0
dft["SibSp"][dft["SibSp"].apply(lambda x: type(x)==float and math.isnan(x))]=0
dft["Fare"][dft["Fare"].apply(lambda x: type(x)==float and math.isnan(x))]=0
df

/tmp/ipykernel_29730/2025783320.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"][df["Age"].apply(math.isnan)]=filled.mean()
/tmp/ipykernel_29730/2025783320.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Cabin"][df["Cabin"].apply(lambda x: type(x)==float and math.isnan(x))]="U"
/tmp/ipykernel_29730/2025783320.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Embarked"][df["Embarked"].apply(lambda x: type(x)==

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name  Sex  \
PassengerId                                                           
1                                      Braund, Mr. Owen Harris    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...    2   
3                                       Heikkinen, Miss. Laina    2   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)    2   
5                                     Allen, Mr. William Henry    1   
...                                                        ...  ...   
887                                      Montvila, Rev. Juozas    1   
888                               Graham, Miss. Margaret Edith    2   
889                   Johnston, Miss. Catherine Helen "Carrie"    2   
890                                      Behr, Mr. Karl Howell    1   
891                                        Dooley, Mr. Patrick    1   

                   Age  SibSp  Parch            Ticket     Fare Cabin  \
PassengerId                                                             
1            22.000000      1      0         A/5 21171   7.2500     U   
2            38.000000      1      0          PC 17599  71.2833   C85   
3            26.000000      0      0  STON/O2. 3101282   7.9250     U   
4            35.000000      1      0            113803  53.1000  C123   
5            35.000000      0      0            373450   8.0500     U   
...                ...    ...    ...               ...      ...   ...   
887          27.000000      0      0            211536  13.0000     U   
888          19.000000      0      0            112053  30.0000   B42   
889          29.699118      1      2        W./C. 6607  23.4500     U   
890          26.000000      0      0            111369  30.0000  C148   
891          32.000000      0      0            370376   7.7500     U   

             Embarked  
PassengerId            
1                  -3  
2                  -1  
3                  -3  
4                  -3  
5                  -3  
...               ...  
887                -3  
888                -3  
889                -3  
890                -1  
891                 1  

[891 rows x 11 columns]

In [5]:
weights = np.array([])
bias = 0
X=df[["SibSp", "Age", "Parch", "Fare", "Pclass"]].to_numpy()
Y=df[["Survived"]].to_numpy()
Y[Y==0]=-1
Xtest=dft[["SibSp", "Age", "Parch", "Fare", "Pclass"]].to_numpy()
# plt.scatter(X[:,0],X[:,1])

In [6]:
def compute_cost(W, b, X, Y, regularization_strength = 10000):
    N = X.shape[0]
    distances = 1 - Y * (X@W+b)
    distances[distances<0] = 0
    hinge_loss = regularization_strength * (np.sum(distances) / N)
    cost = 1 / 2 * (W@W.T) + hinge_loss
    return cost

def calculate_cost_gradient(W, b, X_batch, Y_batch, regularization_strength = 10000):
    if type(Y_batch) == np.float64:
        Y_batch = np.array([Y_batch])
        X_batch = np.array([X_batch])

    distance = 1 - (Y_batch * (X_batch@W + b))
    distance[distance<0] = 0
    # dw = W - (regularization_strength * Y_batch * X_batch) * np.sign(np.abs(distance))
    dw = W - (regularization_strength * Y_batch[0] * X_batch) * np.sign(distance[0])
    return dw

def calculate_bias_cost_gradient(W, b, X_batch, Y_batch, regularization_strength = 10000):
    if type(Y_batch) == np.float64:
        Y_batch = np.array([Y_batch])
        X_batch = np.array([X_batch])

    distance = 1 - (Y_batch * (X_batch@W + b))
    distance[distance<0] = 0
    db = 0
    # dw = W - (regularization_strength * Y_batch * X_batch) * np.sign(np.abs(distance))
    db += - (regularization_strength * Y_batch) * np.sign(distance[0])
    return db

def sgd(weights, bias, X, Y, max_epochs = 5000, cost_threshold = 0.00001, alpha = 0.0000001):
    if weights.shape==(0,):
        weights = np.zeros(X.shape[1])
    nth = 0
    prev_cost = float("inf")
    for epoch in range(1, max_epochs):
        Xt, Yt = shuffle(X, Y)
        for ind, x in enumerate(Xt):
            error = calculate_cost_gradient(weights, bias, x, Yt[ind])
            bias_error = calculate_bias_cost_gradient(weights, bias, x, Yt[ind])
            weights = weights - (alpha * error)
            bias = bias - alpha * bias_error
        if epoch == 2 ** nth or epoch == max_epochs - 1:
            cost = compute_cost(weights, bias, X, Y)
            print("Epoch:",epoch,"Cost:",cost)
            if abs(prev_cost - cost) < cost_threshold * prev_cost:
                return (weights, bias, cost)
            prev_cost = cost
            nth += 1
    return (weights, bias, prev_cost)

def predict(weights, bias, X):
    p=(X@weights+bias)
    p[p>0]=1
    p[p==0]=random.choice([1,0])
    p[p<0]=0
    return p

In [7]:
weights, bias, cost = sgd(weights, bias, X, Y)

Epoch: 1 Cost: 14931950.662328696
Epoch: 2 Cost: 13152826.531265939
Epoch: 4 Cost: 13419973.759175338
Epoch: 8 Cost: 29870805.603566468
Epoch: 16 Cost: 14502883.482134873
Epoch: 32 Cost: 23778949.618212044
Epoch: 64 Cost: 15010130.8633579
Epoch: 128 Cost: 29719454.091167137
Epoch: 256 Cost: 17435902.555705868
Epoch: 512 Cost: 13094646.771415476
Epoch: 1024 Cost: 17671519.400040008
Epoch: 2048 Cost: 16796660.699814867
Epoch: 4096 Cost: 15759874.36514648
Epoch: 4999 Cost: 9758650.412802255


In [8]:
weights, bias

(array([-0.8399429 , -0.05340125,  0.2034545 ,  0.01081154, -1.00940465]),
 array([3.234]))

In [9]:
predict(weights, bias, Xtest)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 0.

In [10]:
lrweights = np.array([[]])
lrbias = np.array([[]])
lrY = np.array(list(map((lambda x: [1,0] if x==1 else [0,1]), Y)))
#activation
def sigmoid(W,b,X):
    Z=X@W.T+b
    return 1/(1+np.exp(-Z))
# cost function
def total_cost(weights, biases, x, y):
    p=sigmoid(weights, biases, x)
    return -np.sum(y*np.log(p)+(1-y)*np.log(1-p)) / len(y[0])

# gradient descent
def fit(weights, biases, x, y, alpha=0.00000001, iters=2000, cost_threshold = 0.00001):
    DATALEN: int = len(y)
    NOUT: int = len(y[0])
    NVARS: int = len(x[0])
    if weights.shape==(1,0):
        weights = np.zeros((NOUT, NVARS))
    if biases.shape==(1,0):
        biases = np.zeros((1, NOUT))
    history = []
    n=0
    prev_cost = float("inf")
    for i in range(iters):
        xt, yt = shuffle(x, y)
        p = sigmoid(weights, biases, xt)
        error = p - yt
        weights -= (error.T@xt / DATALEN) * alpha
        biases -= (np.sum(error) / DATALEN) * alpha
        if i == 2 ** n:
            cost = total_cost(weights, bias, X, Y)
            print("Epoch:",i,"Cost:",cost)
            history.append([i,cost])
            if abs(prev_cost - cost) < cost_threshold * prev_cost:
                return weights, bias, history
            prev_cost = cost
            n += 1
        history.append([i, total_cost(weights, biases, xt, yt)])
    return weights, biases, history

# prediction
def lrpredict(weights, biases, x):
    return sigmoid(weights, biases, x)

def r_squared(prediction, values):
    sstot = np.sum((values-np.mean(values))**2)
    ssres = np.sum((values-prediction)**2)
    return 1-ssres/sstot

In [11]:
print(lrY)
lrweights, lrbias, hist = fit(lrweights, lrbias, X, lrY)

[[0 1]
 [1 0]
 [1 0]
 ...
 [0 1]
 [1 0]
 [0 1]]
Epoch: 1 Cost: 7170.726225455335
Epoch: 2 Cost: 7170.726225455626


In [12]:
for p in lrpredict(lrweights, lrbias, Xtest):
    print(1 if p[0]>p[1] else 0)

0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
1
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
1
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
0
0
0
1
0
0
0
1
0
0
0
1
0
1
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
1
1
0
0
0
0
1
1
0
1
0
0
0
1
0
0
0
0
0
1
0
1
0
0
0
0
1
1
1
0
0
0
0
0
0
0
0
1
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
1
0
1
1
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
1
1
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
1
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
1
0
0
0
1
1
0
1
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
1
1
0
0
0
0
1
0
1
0
0
1
0
1
1
0
0
0
1
0
1
0
1
0
0
1
0
0
0
